### ISSUE TITLE
importSedml method only imports a single task

### ISSUE THREAD

**Issue by gmarupilla** [biosimulators/Biosimulators_COPASI#31]
enable dataModel to import multiple tasks from single SED-ML. 

For refernce: https://github.com/reproducible-biomedical-modeling/Biosimulations_COPASI/blob/89ae725fab181ede716c2c6bada5ec5e9b8ac45a/Biosimulations_copasi/core.py#L99

**Comment by jonrkarr** [comment]
COPASI's support for SED-ML is very ad hoc. Fixed by not using COPASI to parse COMBINE or SED-ML.
