### ISSUE TITLE
Support hybrid RK45 method

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_COPASI#43]
As discussed in #25, this package cannot support the hybrid RK45 method because python-COPASI doesn't support setting the partitioning parameter. @fbergmann please let us know when python-COPASI is updated so we extend support to this package, the COPASI docker image, and all downstream tools such as runBioSimulations.

**Comment by fbergmann** [comment]
@jonrkarr, i've released a new python-copasi package (version 4.30.233), that you can use with the code from issue #25 to set the deterministic reactions.

**Comment by jonrkarr** [comment]
Thanks! I code similar to #25 to implement this. All time course simulation methods and all of their parameters appear to now be working and attached to KiSAO terms.
