### ISSUE TITLE
Improve messages for COPASI errors

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_COPASI#44]
@fbergmann how can I get error information from COPASI to pass this along to users, e.g. when an algorithm fails?

I inherited the following from Akhil, but this doesn't work.
```python
error_message = COPASI.CCopasiMessage.getAllMessageText(True)
```

**Comment by fbergmann** [comment]
there are two methods for doing that, either: 
    
      if not task.process(True): 
          print(task.getProcessWarning())
          print(task.getProcessError())

or if you need more fine grained control: 


    result = task.initializeRaw(COPASI.CCopasiTask.OUTPUT_UI)
    if not result: 
        logging.error("Error while initializing the simulation: " +  
        COPASI.CCopasiMessage.getLastMessage().getText())
    else: 
        result = task.processRaw(use_initial_values)
        if not result: 
            logging.error("Error while running the simulation: " + 
            COPASI.CCopasiMessage.getLastMessage().getText())

whether you want just the last message, or all chronologically is up to you.

**Comment by jonrkarr** [comment]
Thanks. The CLI and image now display error messages from COPASI.
