### ISSUE TITLE
Get values of non-constant parameters

### ISSUE THREAD

**Issue by jonrkarr** [biosimulators/Biosimulators_COPASI#46]
Some simulation experiments (SED documents) need to record non-constant SBML parameters set via assignment rules, event assignments, etc.

@fbergmann @shoops @pmendes What's the syntax to use to get time courses for SBML parameters?

Here's a sketch of the code we're currently using. This only retrieves time courses for SBML species. How does this need to be edited

```python
import COPASI

filename = 'path/to/model.xml'

data_model = COPASI.CRootContainer.addDatamodel()
data_model.importSBML(filename)

task = data_model.getTask('Time-Course')
task.setMethodType(COPASI.CTaskEnum.Method_deterministic)
task.setScheduled(True)

model = data_model.getModel()
problem = task.getProblem()
model.setInitialTime(0.)
problem.setOutputStartTime(0.)
problem.setDuration(10.)
problem.setStepNumber(10)
problem.setTimeSeriesRequested(True)
problem.setAutomaticStepSize(False)
problem.setOutputEvent(False)

result = task.process(True)

time_series = task.getTimeSeries()
```

**Comment by shoops** [comment]
Hello Jonathan,

The time_series contains all non-constant values including fixed values
changed by events.

Thanks,
Stefan

**Comment by jonrkarr** [comment]
@shoops thanks for the quick reply.

Here's a more complete example where the time series doesn't include non-constant parameters set via event assignments. Here's the example model: [model.xml.zip](https://github.com/biosimulators/Biosimulators_COPASI/files/6422996/model.xml.zip) (BIOMD0000000806). The time series doesn't include `d_u`, `d_m1` or `H`. I'm using COPASI 4.30.240.

What parameter do I need to set or function do I need to execute to retrieve the values of these parameters? I tried looking through the COPASI examples and documentation; the required syntax wasn't obvious to me.

```python
import COPASI
import libsbml

filename = 'model.xml'

data_model = COPASI.CRootContainer.addDatamodel()
data_model.importSBML(filename)

task = data_model.getTask('Time-Course')
task.setMethodType(COPASI.CTaskEnum.Method_deterministic)
task.setScheduled(True)

model = data_model.getModel()
problem = task.getProblem()
model.setInitialTime(0.)
problem.setOutputStartTime(0.)
problem.setDuration(10.)
problem.setStepNumber(10)
problem.setTimeSeriesRequested(True)
problem.setAutomaticStepSize(False)
problem.setOutputEvent(False)

result = task.process(True)

time_series = task.getTimeSeries()

# get SBML ids of recorded variables
variable_sbml_ids = []
for i_variable in range(time_series.getNumVariables()):
    variable_sbml_ids.append(time_series.getSBMLId(i_variable, data_model))

# print SBML ids of recorded variables
print(variable_sbml_ids)

# check if non-constant SBML parameters were recorded
non_constant_parameter_sbml_ids = set(['d_u', 'd_m1', 'H'])
non_constant_parameter_sbml_ids.intersection(variable_sbml_ids)

# verify that the non-constant SBML parameters are part of the model
sbml_doc = libsbml.readSBMLFromFile(filename)
sbml_model = sbml_doc.getModel()
for sbml_id in non_constant_parameter_sbml_ids:
    sbml_parameter = sbml_model.getParameter(sbml_id)
    assert sbml_parameter is not None
    assert not sbml_parameter.getConstant()
```

**Comment by shoops** [comment]
Hello Jonathan,

You cannot use the time_series to get those values as they are not state variables of the system. You will have to create a report which contains the observables and variables required from SED-ML file. An exampleson how to proceed can be found at:
https://github.com/copasi/COPASI/blob/develop/copasi/bindings/python/examples/custom_output.py

Stefan

**Comment by jonrkarr** [comment]
Perfect! I would never have been able to guess this myself. I should be able to figure out the rest.

**Comment by shoops** [comment]
Helllo Jonathan, 

I think a better approach would be to let COPASI read the SED-ML directly.  The problem I see is that if SED-ML asks for plot and you are running CopasiSE tor any language bindings he plot will not be generated. I think I have an idea on how to circumvent that. I will talk with @fbergmann about it.

Stefan

**Comment by jonrkarr** [comment]
I started a new issue for the discussion that @shoops started. See #48.

**Comment by shoops** [comment]
This repository will never be obsolete since it provides functionality which is not part of COPASI's core. However making data specified by SED-ML plots and reports available to the calling process is a general feature desirable for language bindings.

**Comment by jonrkarr** [comment]
Done in 4b9c03aac83223c44bd85c26ff1350b7728d7b02.
