### ISSUE TITLE
Mark Steady State Simulations / Scan as supported

### ISSUE THREAD

**Issue by fbergmann** [biosimulators/Biosimulators_COPASI#47]
@jonrkarr COPASI does read SteadyState Simulations  and repeated tasks running steady state from SED-ML. Can we mark these as supported?

**Comment by jonrkarr** [comment]
Closing because this is the same issue as #45.

**Comment by fbergmann** [comment]
i dont think it is the same issue, even basic steady state computation, loading a model simulating to steady state, retrieveing the report. or scan over a parameter, bringing the model to steady state, plotting the result. Would be supported by COPASI on import right now, but is not available through BioSimulation.

**Comment by jonrkarr** [comment]
These functions aren't supported for the reasons outlined in #45. #45 outlines what needs to be done to make this work through runBioSimulations. This includes the subset of things needed to advertise these capabilities through BioSimulators. 

This advertising in BioSimulators also utilizes KiSAO. This is important for connecting the capabilities of tools to the requirements to execute specific SED-ML documents. The advertising can be expanded separately from expanding the capabilities of the docker image. The specifications of tools are structured to be able to capture the different capabilities of different interfaces (ui, api, docker, etc).
