### ISSUE TITLE
copasi_model_obj_common_name needs to be a string

### ISSUE THREAD

**Issue by eagmon** [biosimulators/Biosimulators_COPASI#53]
[this line in core.py](https://github.com/biosimulators/Biosimulators_COPASI/blob/e65de13e8665fae8e4c62b8c3d14a4d00840bc8c/biosimulators_copasi/core.py#L430) can return an invalid model name and leads to an error: 
`TypeError: Wrong number or type of arguments for overloaded function 'new_CRegisteredCommonName'.` 
I found this can be fixed by simply converting it to a string. Would be happy to open a PR if I'm given access.

**Comment by jonrkarr** [comment]
I'm not sure how this could fail. It sounds like the importing of the model (L327) might have failed and the error wasn't caught. What happens if you import the model that you're trying into the COPASI UI?

**Comment by fbergmann** [comment]
The correct fix would be to call `copasi_model.getValueReference().getCN().getString()` sorry for the inconvenience.

**Comment by eagmon** [comment]
Thank you @fbergmann @jonrkarr!

**Comment by jonrkarr** [comment]
This will be released as `0.1.35` in a few minutes.
