### ISSUE TITLE
Incorrectly raised Exception regarding number of time points

### ISSUE THREAD

**Issue by leon9812** [biosimulators/Biosimulators_COPASI#66]
The NotImplementedError (Time course must specify an integer number of time points) in [core.py#L197](https://github.com/biosimulators/Biosimulators_COPASI/blob/a18afb6193ade75c69fa0153a0c5e16958a77f4f/biosimulators_copasi/core.py#L197) is raised for specific integer numbers of steps in combination with certain time values.

Example ([core.py#L191](https://github.com/biosimulators/Biosimulators_COPASI/blob/a18afb6193ade75c69fa0153a0c5e16958a77f4f/biosimulators_copasi/core.py#L191)):
```python
# sim.number_of_points = 500
# sim.initial_time = 0.0
# sim.output_start_time = 0.0
# sim.output_end_time = 1.1
step_number = (
    sim.number_of_points
    * (sim.output_end_time - sim.initial_time)
    / (sim.output_end_time - sim.output_start_time)
)
```
Even though the number of points is an integer, the step_number now has a value of 499.99999999999994, which raises the exception.

One way to fix this would be to add more parentheses:
```python
step_number = (
    sim.number_of_points
    * (
        (sim.output_end_time - sim.initial_time)
        / (sim.output_end_time - sim.output_start_time)
    )
)
```

**Comment by AlexPatrie** [comment]
I can confirm that this works. Fix to come!
