### ISSUE TITLE
Biosimulators copasi gives incorrect results that normal copasi doesn't 

### ISSUE THREAD

**Issue by luciansmith** [biosimulators/Biosimulators_COPASI#71]
The attached OMEX files all produce different results on copasi-on-biosimulations than they do for copasi-on-my-desktop (or, for that matter, from tellurium-on-biosimulations).  

[BIOMD0000000005.omex.zip](https://github.com/biosimulators/Biosimulators_COPASI/files/11519003/BIOMD0000000005.omex.zip)
[BIOMD0000000006.omex.zip](https://github.com/biosimulators/Biosimulators_COPASI/files/11519025/BIOMD0000000006.omex.zip)
[BIOMD0000000007.omex.zip](https://github.com/biosimulators/Biosimulators_COPASI/files/11519026/BIOMD0000000007.omex.zip)

The phenotype is the same for all:  a value that should change in time instead is fixed and doesn't change.  For Biomodels 5, the variable in question is YT, aka 'total_cyclin'.  You can see the difference in 

https://run.biosimulations.org/runs/64406c7ad5954382281dde42#tab=viz (copasi, incorrect)
vs
https://run.biosimulations.org/runs/64669bea9a62a8be53f457d1#tab=viz (tellurium, correct, and matches my copy of copasi, v4.36)

Biomodels 6:
https://run.biosimulations.org/runs/64406c7a44d76b2ce805707f#tab=viz
https://run.biosimulations.org/runs/64669bea49c0d898ffdaa536#tab=viz

Biomodels 7:
https://run.biosimulations.org/runs/64406c7be039ed31faa8dc62#tab=viz
https://run.biosimulations.org/runs/64669beb0dcacb5567885fc0#tab=viz

**Comment by luciansmith** [comment]
@fbergmann : Just in case you have an idea of how someone might accidentally tell Copasi to leave something fixed.

**Comment by fbergmann** [comment]
I think the biosimulator_copasi does use the utils to apply changes, rather than let COPASI do it. So the error would have to be fixed there, as it would apply to more biosimulators.

**Comment by luciansmith** [comment]
This is now fixed!
